### PR TITLE
Use screen to run rpc/miner in the background without multiple ssh connections

### PR DESCRIPTION
**Pull request by aakilfernandes**
This is especially important so that if your SSH connection breaks, your rpc/miner keeps going

### CODE REVIEW

**Comment by angelomilan** [comment]
That's great! When do you use screen? before or after geth --rpc console command?

**Comment by terzim** [comment]
Angelo have a look here: http://stackoverflow.com/questions/21193988/keep-server-running-on-ec2-instance-after-ssh-is-terminated

**Comment by terzim** [comment]
Also see my conversation with Adam Rotello on forum ethereum: 

AdamRotello August 2
First off, thanks for putting up that AWS mining guide. It's been immensly helpful. You mention in the AWS writeup that you can close the ssh terminal and the mining process will still run. When you ssh back into the machine how can you identify that the miner is still doing work? Thanks.

terzim
terzim 12:03PM
Hi Adam. No worries. I will get back to you sooner rather than later on this. We are writing a little clarification about this in the note.

terzim
terzim 12:05PM
essentially the proper solution appears to run a "screen" command to keep the server running even if you close the connection. More details int he guide.

AdamRotello
AdamRotello 12:07PM
Yeah, I figured it out and used tmux instead of screen. Thanks.

**Comment by angelomilan** [comment]
@terzim so please edit the guide accordingly

**Comment by terzim** [comment]
@angelomilan i will try to tonight, there is a strange message saying:

"This branch has conflicts that must be resolved
Use the command line to resolve conflicts before continuing"

**Comment by terzim** [comment]
Hi @aakilfernandes Aakli, 

I updated the guide using your writeup. Thanks for the comment, all credit goes to you.

**Pull request closed without merging**
